#!/bin/bash

if [ $# -lt 3 ]; then
  echo -e "Find max among the numbers\nUsage: ./seven number1 number2 number3"
  exit
fi

if [ $1 -lt $2 ]; then
  if [ $2 -lt $3 ]; then
    echo "largest number is $3"
  else
    echo "largest number is $2"
  fi
elif [ $1 -lt $3 ]; then
  echo "largest number is $3"
else
  echo "largest number is $1"
fi